//
//  ContriesDict.swift
//  Coronavirus2019
//
//  Created by Mia Tsung on 3/28/20.
//  Copyright © 2020 Mia Tsung. All rights reserved.
//

import Foundation

class ContriesDict {
    
    func for(name : String) -> String? {
        
    }
}

//
//[ "USA",
//"Italy",
//"Spain",
//"Germany",
//"France",
//"Iran",
//"UK",
//"Switzerland",
//"Netherlands",
//"S. Korea",
//"Belgium",
//"Austria",
//"Turkey",
//"Canada",
//"Portugal",
//"Norway",
//"Brazil",
//"Australia",
//"Israel",
//"Sweden",
//"Czechia",
//"Ireland",
//"Malaysia",
//"Denmark",
//"Chile",
//"Luxembourg",
//"Ecuador",
//"Japan",
//"Poland",
//"Pakistan",
//"Romania",
//"Russia",
//"Thailand",
//"Saudi Arabia",
//"South Africa",
//"Finland",
//"Indonesia",
//"Philippines",
//"Greece",
//"India",
//"Iceland",
//"Singapore",
//"Panama",
//"Argentina",
//"Dominican Republic",
//"Mexico",
//"lat": 0,
//"Slovenia",
//"Peru",
//"Serbia",
//"Croatia",
//"Estonia",
//"Colombia",
//"Qatar",
//"Egypt",
//"Hong Kong",
//"Iraq",
//"Bahrain",
//"UAE",
//"Algeria",
//"New Zealand",
//"Lebanon",
//"Armenia",
//"Morocco",
//"Lithuania",
//"Ukraine",
//"Hungary",
//"Bulgaria",
//"Andorra",
//"Latvia",
//"Costa Rica",
//"Slovakia",
//"Taiwan",
//"Tunisia",
//"Bosnia",
//"Uruguay",
//"Jordan",
//"Macedonia",
//"Kuwait",
//"Moldova, Republic of",
//"Kazakhstan",
//"San Marino",
//"Burkina Faso",
//"Albania",
//"Réunion",
//"Azerbaijan",
//"Cyprus",
//"Vietnam",
//"Faroe Islands",
//"Oman",
//"Malta",
//"Ghana",
//"Senegal",
//"Brunei",
//"Cuba",
//"Venezuela, Bolivarian Republic of",
//"Sri Lanka",
//"Afghanistan",
//"Uzbekistan",
//"Guadeloupe",
//"Mauritius",
//"Côte d'Ivoire",
//"Cambodia",
//"Palestinian Territory, Occupied",
//"Channel Islands",
//"Nigeria",
//"Honduras",
//"Belarus",
//"Martinique",
//"Cameroon",
//"Georgia",
//"Montenegro",
//"Trinidad and Tobago",
//"Bolivia",
//"Congo, the Democratic Republic of the",
//"Mayotte",
//"Rwanda",
//"Kyrgyzstan",
//"Paraguay",
//"Gibraltar",
//"Liechtenstein",
//"Bangladesh",
//"Aruba",
//"Monaco",
//"Kenya",
//"Guatemala",
//"Macao",
//"Isle of Man",
//"Jamaica",
//"French Polynesia",
//"Uganda",
//"French Guiana",
//"Zambia",
//"Barbados",
//"Madagascar",
//"Togo",
//"El Salvador",
//"Mali",
//"Bermuda",
//"Ethiopia",
//"Maldives",
//"New Caledonia",
//"Djibouti",
//"Tanzania, United Republic of",
//"Equatorial Guinea",
//"Mongolia",
//"Dominica",
//"Saint Martin",
//"Niger",
//"Bahamas",
//"Greenland",
//"Swaziland",
//"Cayman Islands",
//"Curacao",
//"Guyana",
//"Guinea",
//"Haiti",
//"Lao People's Democratic Republic",
//"Mozambique",
//"Myanmar",
//"Namibia",
//"Seychelles",
//"Suriname",
//"Gabon",
//"Zimbabwe",
//"Antigua and Barbuda",
//"Grenada",
//"Benin",
//"Eritrea",
//"Holy See (Vatican City State)",
//"Cabo Verde",
//"Sudan",
//"Nepal",
//"Angola",
//"Fiji",
//"Mauritania",
//"Montserrat",
//"St. Barth",
//"Syrian Arab Republic",
//"Nicaragua",
//"Congo",
//"Turks and Caicos Islands",
//"Gambia",
//"Bhutan",
//"Central African Republic",
//"Chad",
//"Liberia",
//"Libyan Arab Jamahiriya",
//"Saint Lucia",
//"Sint Maarten",
//"Somalia",
//"lat": 0,
//"Anguilla",
//"Belize",
//"British Virgin Islands",
//"Guinea-Bissau",
//"Saint Kitts and Nevis",
//"Papua New Guinea",
//"Saint Vincent and the Grenadines",
//"Timor-Leste",
//"China" ]
