//
//  CountriesDict.swift
//  Coronavirus2019
//
//  Created by Mia Tsung on 3/29/20.
//  Copyright © 2020 Mia Tsung. All rights reserved.
//

import UIKit

class CountriesDict {
    static let NAMES : [String: String] = [
        "Global": "全球",
        "USA": "美国",
        "Italy": "意大利",
        "Spain": "西班牙",
        "Germany": "德国",
        "France": "法国",
        "Iran": "伊朗",
        "UK": "英国",
        "Switzerland": "瑞士",
        "Netherlands": "荷兰",
        "Belgium": "比利时",
        "S. Korea": "韩国",
        "Turkey": "土耳其",
        "Austria": "奥地利",
        "Canada": "加拿大",
        "Portugal": "葡萄牙",
        "Norway": "挪威",
        "Israel": "以色列",
        "Brazil": "巴西",
        "Australia": "澳大利亚",
        "Sweden": "瑞典",
        "Czechia": "捷克",
        "Ireland": "爱尔兰",
        "Malaysia": "马来西亚",
        "Denmark": "丹麦",
        "Chile": "智利",
        "Luxembourg": "卢森堡",
        "Ecuador": "厄瓜多尔",
        "Japan": "日本",
        "Poland": "波兰",
        "Romania": "罗马尼亚",
        "Pakistan": "巴基斯坦",
        "Russia": "俄罗斯",
        "Philippines": "菲律宾",
        "Thailand": "泰国",
        "Saudi Arabia": "沙特阿拉伯",
        "Indonesia": "印度尼西亚",
        "Finland": "芬兰",
        "South Africa": "南非",
        "Greece": "希腊",
        "India": "印度",
        "Iceland": "冰岛",
        "Panama": "巴拿马",
        "Dominican Republic": "多明尼加共和国",
        "Peru": "秘鲁",
        "Mexico": "墨西哥",
        "Singapore": "新加坡",
        "Argentina": "阿根廷",
        "Serbia": "塞尔维亚",
        "Slovenia": "斯洛文尼亚",
        "Croatia": "克罗地亚",
        "Diamond Princess": "钻石公主",
        "Estonia": "爱沙尼亚",
        "Hong Kong": "香港",
        "Qatar": "卡塔尔",
        "Egypt": "埃及",
        "Colombia": "哥伦比亚",
        "UAE": "阿联酋",
        "Iraq": "伊拉克",
        "New Zealand": "新西兰",
        "Algeria": "阿尔及利亚",
        "Bahrain": "巴林",
        "Morocco": "摩洛哥",
        "Lithuania": "立陶宛",
        "Lebanon": "黎巴嫩",
        "Armenia": "亚美尼亚",
        "Ukraine": "乌克兰",
        "Hungary": "匈牙利",
        "Latvia": "拉脱维亚",
        "Bulgaria": "保加利亚",
        "Andorra": "安道尔",
        "Bosnia and Herzegovina": "波黑",
        "Slovakia": "斯洛伐克",
        "Uruguay": "乌拉圭",
        "Taiwan": "台湾",
        "Costa Rica": "哥斯达黎加",
        "Tunisia": "突尼斯",
        "Moldova": "摩尔多瓦",
        "North Macedonia": "北马其顿",
        "Jordan": "约旦",
        "Kuwait": "科威特",
        "Kazakhstan": "哈萨克斯坦",
        "San Marino": "圣马力诺",
        "Burkina Faso": "布基纳法索",
        "Cyprus": "塞浦路斯",
        "Albania": "阿尔巴尼亚",
        "Azerbaijan": "阿塞拜疆",
        "Vietnam": "越南",
        "Réunion": "留尼旺",
        "Oman": "阿曼",
        "Faeroe Islands": "法罗群岛",
        "Ghana": "加纳",
        "Malta": "马耳他",
        "Uzbekistan": "乌兹别克斯坦",
        "Senegal": "塞内加尔",
        "Ivory Coast": "科特迪瓦",
        "Cuba": "古巴",
        "Brunei": "文莱",
        "Afghanistan": "阿富汗",
        "Venezuela": "委内瑞拉",
        "Sri Lanka": "斯里兰卡",
        "Honduras": "洪都拉斯",
        "Palestine": "巴勒斯坦",
        "Mauritius": "毛里求斯",
        "Cambodia": "柬埔寨",
        "Guadeloupe": "瓜德罗普岛",
        "Channel Islands": "海峡群岛",
        "Nigeria": "尼日利亚",
        "Belarus": "白俄罗斯",
        "Martinique": "马提尼克岛",
        "Cameroon": "喀麦隆",
        "Georgia": "格鲁吉亚",
        "Montenegro": "黑山共和国",
        "Kyrgyzstan": "吉尔吉斯斯坦",
        "Bolivia": "玻利维亚",
        "Trinidad and Tobago": "特立尼达和多巴哥",
        "DRC": "刚果民主共和国",
        "Gibraltar": "直布罗陀",
        "Mayotte": "马约特岛",
        "Rwanda": "卢旺达",
        "Paraguay": "巴拉圭",
        "Liechtenstein": "列支敦士登",
        "Aruba": "阿鲁巴岛",
        "Bangladesh": "孟加拉国",
        "Monaco": "摩纳哥",
        "Kenya": "肯尼亚",
        "Isle of Man": "马恩岛",
        "Madagascar": "马达加斯加",
        "Macao": "澳门",
        "Guatemala": "危地马拉",
        "Jamaica": "牙买加",
        "French Polynesia": "法属波利尼西亚",
        "Uganda": "乌干达",
        "Zambia": "赞比亚",
        "French Guiana": "法属圭亚那",
        "Barbados": "巴巴多斯",
        "Togo": "多哥",
        "El Salvador": "萨尔瓦多",
        "Bermuda": "百慕大",
        "Ethiopia": "埃塞俄比亚",
        "Congo": "刚果",
        "Mali": "马里",
        "Niger": "尼日尔",
        "Maldives": "马尔代夫",
        "Guinea": "几内亚",
        "Haiti": "海地",
        "New Caledonia": "新喀里多尼亚",
        "Djibouti": "吉布地",
        "Tanzania": "坦桑尼亚",
        "Equatorial Guinea": "赤道几内亚",
        "Mongolia": "蒙古",
        "Bahamas": "巴哈马",
        "Dominica": "多米尼加",
        "Namibia": "纳米比亚",
        "Saint Martin": "圣马丁",
        "Greenland": "格陵兰",
        "Myanmar": "缅甸",
        "Syria": "叙利亚",
        "Grenada": "格林纳达",
        "Eswatini": "埃斯瓦蒂尼",
        "Cayman Islands": "开曼群岛",
        "Curaçao": "库拉索",
        "Guyana": "圭亚那",
        "Laos": "老挝",
        "Libya": "利比亚",
        "Mozambique": "莫桑比克",
        "Seychelles": "塞舌尔",
        "Suriname": "苏里南",
        "Angola": "安哥拉",
        "Gabon": "加蓬",
        "Zimbabwe": "津巴布韦",
        "Antigua and Barbuda": "安提瓜和巴布达",
        "Cabo Verde": "佛得角",
        "Sudan": "苏丹",
        "Benin": "贝宁",
        "Eritrea": "厄立特里亚",
        "Vatican City": "梵蒂冈城",
        "Sint Maarten": "圣马丁",
        "Nepal": "尼泊尔",
        "Fiji": "斐济",
        "Mauritania": "毛里塔尼亚",
        "Montserrat": "蒙特塞拉特",
        "St. Barth": "圣巴特",
        "Nicaragua": "尼加拉瓜",
        "Bhutan": "不丹",
        "Saint Lucia": "圣卢西亚",
        "Turks and Caicos": "特克斯和凯科斯群岛",
        "Gambia": "冈比亚",
        "CAR": "中非",
        "Chad": "乍得",
        "Liberia": "利比里亚",
        "Somalia": "索马里",
        "MS Zaandam": "赞丹女士",
        "Anguilla": "安圭拉岛",
        "Belize": "伯利兹",
        "British Virgin Islands": "英属维尔京群岛",
        "Guinea-Bissau": "几内亚比绍",
        "Saint Kitts and Nevis": "圣基茨和尼维斯",
        "Papua New Guinea": "巴布亚新几内亚",
        "St. Vincent Grenadines": "圣文森特格林纳丁斯",
        "Timor-Leste": "东帝汶",
        "China": "中国",
        "Botswana": "博茨瓦纳"
    ]
}
